#!/bin/sh
# rezip-rvem.sh — timestamped .7z backup of RVLV_EMUL source tree.
# Excludes:
#   - .git (GitHub is the history backup)
#   - build artifacts (build/, *.elf, *.o, *.a) — regenerated by build.sh
#   - buildroot/ — entire buildroot tree (can be re-downloaded, ~2GB)
#   - musl-build/, musl-install/ — can be regenerated
#   - initramfs/, initramfs_test.cpio* — runtime/generated
#   - 9p_share/ — runtime share directory
#   - xv6-riscv/ — git submodule, re-cloned from upstream
#   - *.log files — disposable logs
#   - prisc_x, prisc_x_linux, prisc_x_bare.elf, bare_test.elf — compiled binaries
# Deletes previous .7z so only newest is kept.

set -e
cd "$(dirname "$0")"
SRC="RVLV_EMUL"
OUT="${SRC}_$(date +%Y%m%d-%H%M%S).7z"

rm -f ${SRC}_*.7z

7z a -mx=5 "$OUT" "$SRC" \
    -xr'!.git' \
    -xr'!build' \
    -xr'!buildroot' \
    -xr'!musl-build' \
    -xr'!musl-install' \
    -xr'!initramfs' \
    -xr'!initramfs_test.cpio*' \
    -xr'!9p_share' \
    -xr'!xv6-riscv' \
    -xr'!*.log' \
    -xr'!prisc_x' -xr'!prisc_x_linux' -xr'!prisc_x_bare.elf' -xr'!bare_test.elf' \
    -xr'!*.elf' -xr'!*.o' -xr'!*.a' \
    -xr'!*.raw' -xr'!*.bin' \
    -xr'!*.seq' \
    -xr'!*.frame.txt'
echo "OK $OUT"